# Generated by Django 2.0.8 on 2018-11-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('artist', models.CharField(max_length=500)),
                ('album', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('blurb', models.CharField(max_length=2000)),
            ],
        ),
    ]
